[project]
name = "ml-utils"
version = "0.1.0"
description = "ML utils dump"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "torch>=2.7.0",
]

[project.optional-dependencies]
dev = [
    "kitcat>=1.2.1",
]
